# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 第 1 步：设置 JDK 的版本为 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: 第 2 步：使用 Maven 构建
      run: mvn -B package --file pom.xml

    - name: 第 3 步：拷贝 jar 包到服务器
      uses: appleboy/scp-action@master
      with:
        host: dance8.fun
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "target/*.jar"
        target: "/root/github-action/suanfa8.jar"  # 服务器上的目标路径

    - name: 第 4 步：在服务器上启动 SpringBoot 项目
      uses: appleboy/ssh-action@master
      with:
        host: dance8.fun
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: nohup java -jar /root/github-action//suanfa8.jar > /dev/null 2>&1 &  # 启动SpringBoot
